// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// Firebase project: bluff-catch
// Run `flutterfire configure` to regenerate with actual production values.
//
// For emulator testing, only projectId matters — the SDK uses the emulator
// host override and never makes real network calls in debug mode.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // These values are valid for emulator-only use.
  // Replace with real values from `flutterfire configure` before production.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANokJumjed81_GB0LklcEmwJJbXkseKvA',
    appId: '1:1019004615710:web:661c147cbfa9baf768020f',
    messagingSenderId: '1019004615710',
    projectId: 'bluff-catch',
    authDomain: 'bluff-catch.firebaseapp.com',
    databaseURL: 'https://bluff-catch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluff-catch.firebasestorage.app',
    measurementId: 'G-PB7SHPB754',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKJ6u5V9ccNHjOGLtykTcqqaRGEksYFy4',
    appId: '1:1019004615710:android:07bde03a63697d5968020f',
    messagingSenderId: '1019004615710',
    projectId: 'bluff-catch',
    databaseURL: 'https://bluff-catch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluff-catch.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgcI25Mgejbiuk2yGU3uEABpmtmlIVcno',
    appId: '1:1019004615710:ios:751c944572a3fd0868020f',
    messagingSenderId: '1019004615710',
    projectId: 'bluff-catch',
    databaseURL: 'https://bluff-catch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluff-catch.firebasestorage.app',
    androidClientId: '1019004615710-bnqs61hlrkpdm7ekspdr0bd2uc51f6vq.apps.googleusercontent.com',
    iosClientId: '1019004615710-0nhkl6f4ta4hnalhkc23h1n2jf4rm880.apps.googleusercontent.com',
    iosBundleId: 'com.bluffcatch.bluffCatch',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgcI25Mgejbiuk2yGU3uEABpmtmlIVcno',
    appId: '1:1019004615710:ios:751c944572a3fd0868020f',
    messagingSenderId: '1019004615710',
    projectId: 'bluff-catch',
    databaseURL: 'https://bluff-catch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluff-catch.firebasestorage.app',
    androidClientId: '1019004615710-bnqs61hlrkpdm7ekspdr0bd2uc51f6vq.apps.googleusercontent.com',
    iosClientId: '1019004615710-0nhkl6f4ta4hnalhkc23h1n2jf4rm880.apps.googleusercontent.com',
    iosBundleId: 'com.bluffcatch.bluffCatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANokJumjed81_GB0LklcEmwJJbXkseKvA',
    appId: '1:1019004615710:web:743348a93568bb3a68020f',
    messagingSenderId: '1019004615710',
    projectId: 'bluff-catch',
    authDomain: 'bluff-catch.firebaseapp.com',
    databaseURL: 'https://bluff-catch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluff-catch.firebasestorage.app',
    measurementId: 'G-DLD5VC1YVQ',
  );
}
